
DROP TABLE IF EXISTS Variant_Attribute;
DROP TABLE IF EXISTS Product_Attribute;
DROP TABLE IF EXISTS Product_Category;
DROP TABLE IF EXISTS Variant;
DROP TABLE IF EXISTS Product;
DROP TABLE IF EXISTS Attribute;
DROP TABLE IF EXISTS Category;
